/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingsystem;

import java.awt.Image;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author GTB Student
 */
public class adduser extends javax.swing.JInternalFrame {
DefaultTableModel mymodel;
JFileChooser myfilechooser;
    File myfile;
    /**
     * Creates new form adduser
     */
    public adduser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Add Employee");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 153, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 35, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 48, 17);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 90, 185, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("City");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 24, 17);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(210, 130, 185, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("State");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 32, 17);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(210, 170, 185, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Phone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 210, 39, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Username");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 330, 61, 17);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(210, 330, 185, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 370, 58, 17);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(210, 370, 185, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Gender");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 250, 44, 17);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(210, 250, 80, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(310, 250, 90, 23);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Country");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 290, 51, 17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "India", "USA", "UK", "China", "Japan", "Australia", "Others" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(210, 290, 190, 30);

        jButton1.setText("Add User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 530, 110, 30);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 210, 120, 30);

        jButton3.setText("Delete");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 530, 80, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("User Type");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 410, 62, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Admin", "Employee" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(210, 410, 190, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Username", "Phone"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(670, 210, 452, 402);

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(420, 50, 120, 30);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(210, 210, 190, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Date of Birth");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 460, 110, 30);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(210, 470, 190, 20);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(780, 20, 150, 150);

        jButton5.setText("Upload");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(940, 103, 90, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(210, 50, 190, 30);

        setBounds(0, 0, 1192, 654);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String filename="";
        if(myfile!=null)
        {
            filename = "uploads\\"+new Date().getTime() + myfile.getName();//Date.getTime() added for unique file name.
            int i;
            FileInputStream rd = null;
            FileOutputStream outs = null;
            try {

                rd = new FileInputStream(myfile);
                outs = new FileOutputStream(filename);//writing the new file in 'Images' folder, in the project

                byte[] b = new byte[2048];
                while ((i = rd.read(b)) !=-1) {
                    outs.write(b, 0, i);

                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
            } finally {
                try {
                    rd.close();
                    outs.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "error in closing file" + e.getMessage());
                }
            }
        }
        else
        {
            filename="uploads\\default.jpg";
        }


//
        String url = "jdbc:mysql://localhost/billingdb";
        try
        {
          Connection myconn =  DriverManager.getConnection(url, "mydbuser", "123");
          try
          {
            
              boolean flag=true;
              
              if(jTextField1.getText().length()<4)
              {
                  flag=false;
                  JOptionPane.showMessageDialog(rootPane, "Enter proper name");
              }
              else if(jComboBox1.getSelectedIndex()==0)
              {
                  flag=false;
                  JOptionPane.showMessageDialog(rootPane, "Please choose Country");
              }
              else if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false)
              {
                  flag=false;
                  JOptionPane.showMessageDialog(rootPane, "Please choose gender");
              }
              
              if(flag==true)
              {
                    SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                    String q = "insert into adduser values(?,?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement myst =  myconn.prepareStatement(q);
                    myst.setString(1, jTextField1.getText());
                    myst.setString(2, jTextField2.getText());
                    myst.setString(3, jTextField3.getText());
                    myst.setString(4, jTextField4.getText());
                    myst.setString(5, jFormattedTextField1.getText());
                    if(jRadioButton1.isSelected())
                    {
                      myst.setString(6, "Male");
                    }
                    else if(jRadioButton2.isSelected())
                    {
                      myst.setString(6, jRadioButton2.getText());
                    }
                    myst.setString(7, jComboBox1.getSelectedItem().toString());
                    myst.setString(8, jTextField6.getText());
                    myst.setString(9, jPasswordField2.getText());
                    myst.setString(10, jComboBox2.getSelectedItem().toString());
                    
                    String dob = myformat.format(jDateChooser1.getDate());
                    
                    myst.setString(11, dob);
                    myst.setString(12, filename);
                    int res = myst.executeUpdate();
                    if(res>0)
                    {
                        JOptionPane.showMessageDialog(rootPane, "User added successfully ");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "User not added successfully ");
                    }
               }
            
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
          }
          finally
          {
              myconn.close();
          }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String url = "jdbc:mysql://localhost/billingdb";
        try
        {
          Connection myconn =  DriverManager.getConnection(url, "mydbuser", "123");
          try
          {
                String q = "select * from adduser where phonenumber=?";
                PreparedStatement myst =  myconn.prepareStatement(q);
                myst.setString(1, jFormattedTextField1.getText());
                
                ResultSet myres = myst.executeQuery();
                if(myres.next())
                {
                    jTextField1.setText(myres.getString("name"));
                    jTextField2.setText(myres.getString("address"));
                    jTextField3.setText(myres.getString("city"));
                    jTextField4.setText(myres.getString("state"));
                    if(myres.getString("gender").equalsIgnoreCase("male"))
                    {
                        jRadioButton1.setSelected(true);
                    }
                    else if(myres.getString("gender").equalsIgnoreCase("female"))
                    {
                        jRadioButton2.setSelected(true);
                    }
                    jComboBox1.setSelectedItem(myres.getString("country"));
                    jTextField6.setText(myres.getString("username"));
                    jPasswordField2.setText(myres.getString("password"));
                    jDateChooser1.setDate(myres.getDate("dob"));
                    jButton3.setEnabled(true);
                    String ofile=myres.getString("userpic");
                    Image simg = ImageIO.read( new File(ofile)).getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_DEFAULT);
                    jLabel13.setIcon(new ImageIcon(simg)); 
                    
                }
                else
                {
                  JOptionPane.showMessageDialog(rootPane, "Incorrect phone number");
                  clearfields();
                }
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
          }
          finally
          {
              myconn.close();
          }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      String url = "jdbc:mysql://localhost/billingdb";
        try
        {
          Connection myconn =  DriverManager.getConnection(url, "mydbuser", "123");
          try
          {
                String nmm = "%" + jTextField1.getText() + "%";
                String q = "select * from adduser where name like ?";
                PreparedStatement myst =  myconn.prepareStatement(q);
                myst.setString(1, nmm);
                
                ResultSet myres = myst.executeQuery();
                mymodel = (DefaultTableModel)jTable1.getModel();
                mymodel.setRowCount(0);
                while(myres.next())
                {
                 String nm = myres.getString("name");
                 String add = myres.getString("address");
                 String un = myres.getString("username");
                 String ph = myres.getString("phonenumber");
                 Object myrow[] = {nm,add,un,ph};
                 mymodel.addRow(myrow);
                }
                
                if(mymodel.getRowCount()==0)
                {
                    mymodel.setRowCount(0);
                    JOptionPane.showMessageDialog(rootPane, "No records available");
                     jButton3.setEnabled(false);
                      clearfields();
                }
               
               
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
          }
          finally
          {
              myconn.close();
          }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    void clearfields()
    {
                    
                   jTextField1.setText(null);
                    jTextField2.setText("");
                    jTextField3.setText(null);
                    jTextField4.setText(null);
                    jFormattedTextField1.setText(null);
                    buttonGroup1.clearSelection();
                    jComboBox1.setSelectedIndex(0);
                     jTextField6.setText(null);
                    jPasswordField2.setText(null);
                     jButton3.setEnabled(false);
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String un = jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
        
        String url = "jdbc:mysql://localhost/billingdb";
        try
        {
          Connection myconn =  DriverManager.getConnection(url, "mydbuser", "123");
          try
          {
                String q = "select * from adduser where username=?";
                PreparedStatement myst =  myconn.prepareStatement(q);
                myst.setString(1, un);
                
                ResultSet myres = myst.executeQuery();
                if(myres.next())
                {
                    jTextField1.setText(myres.getString("name"));
                    jTextField2.setText(myres.getString("address"));
                    jTextField3.setText(myres.getString("city"));
                    jTextField4.setText(myres.getString("state"));
                    jFormattedTextField1.setText(myres.getString("phonenumber"));
                    if(myres.getString("gender").equalsIgnoreCase("male"))
                    {
                        jRadioButton1.setSelected(true);
                    }
                    else if(myres.getString("gender").equalsIgnoreCase("female"))
                    {
                        jRadioButton2.setSelected(true);
                    }
                    jComboBox1.setSelectedItem(myres.getString("country"));
                    jTextField6.setText(myres.getString("username"));
                    jPasswordField2.setText(myres.getString("password"));
                     jDateChooser1.setDate(myres.getDate("dob"));
                    jButton3.setEnabled(true);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Incorrect phone number");
                    jTextField1.setText(null);
                    jTextField2.setText("");
                    jTextField3.setText(null);
                    jTextField4.setText(null);
                    buttonGroup1.clearSelection();
                    jComboBox1.setSelectedIndex(0);
                     jTextField6.setText(null);
                    jPasswordField2.setText(null);
                    
                }
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
          }
          finally
          {
              myconn.close();
          }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String url = "jdbc:mysql://localhost/billingdb";
        try
        {
          Connection myconn =  DriverManager.getConnection(url, "mydbuser", "123");
          try
          {
                String q = "delete from adduser where username=?";
                PreparedStatement myst =  myconn.prepareStatement(q);
                myst.setString(1, jTextField6.getText());
                
                int myres = myst.executeUpdate();
                
                if(myres>0)
                {
                     JOptionPane.showMessageDialog(rootPane, "User Deleted Successfully");
                     clearfields();
                     mymodel.setRowCount(0);
                     
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "User not deleted Successfully");
                }
               
          }
          catch(Exception e)
          {
              JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
          }
          finally
          {
              myconn.close();
          }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Error in connection " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       myfilechooser=new JFileChooser();
        myfilechooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory())
                {
                    return true;
                }
                String accepted[]={"png","jpg","gif","bmp","jpeg"};
                String extension=f.getName().substring(f.getName().lastIndexOf(".")+1);
                for(String a:accepted)
                {
                    if(a.equalsIgnoreCase(extension))
                    {
                        return true;
                    }
                    
                }
                return false;
            }

            @Override
            public String getDescription() {
                return "All Picture Files";
            }
        });
        int answer=myfilechooser.showOpenDialog(this);
      
           
        if(answer==JFileChooser.APPROVE_OPTION)
        {
            myfile=myfilechooser.getSelectedFile();
            String fn = myfile.toString();
            try
            {
                Image simg = ImageIO.read(new File(fn)).getScaledInstance( jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_DEFAULT);
                jLabel13.setIcon(new ImageIcon(simg)); 
               
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(rootPane, "Cannot read image");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
